from enum import StrEnum


class ScenarioStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    ARCHIVED = "ARCHIVED"


class StopType(StrEnum):
    DELIVERY = "DELIVERY"
    RETURN = "RETURN"
    PICKUP = "PICKUP"


class StopStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class VehicleStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    ACTIVE = "ACTIVE"
    MAINTENANCE = "MAINTENANCE"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    VALIDATING = "VALIDATING"
    OPTIMIZING = "OPTIMIZING"
    VALIDATING_ROUTE = "VALIDATING_ROUTE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RouteAction(StrEnum):
    DEPOT_START = "DEPOT_START"
    DELIVER = "DELIVER"
    PICKUP = "PICKUP"
    RETURN = "RETURN"
    DEPOT_END = "DEPOT_END"


class EventType(StrEnum):
    RUN_CREATED = "RUN_CREATED"
    VALIDATING = "VALIDATING"
    LOADING_DATA = "LOADING_DATA"
    CLUSTERING = "CLUSTERING"
    BUILDING_ROUTE = "BUILDING_ROUTE"
    OPTIMIZING = "OPTIMIZING"
    CHECKING_CONSTRAINTS = "CHECKING_CONSTRAINTS"
    CALCULATING_METRICS = "CALCULATING_METRICS"
    PERSISTING = "PERSISTING"
    ROUTE_READY = "ROUTE_READY"
    AI_ANALYSIS_STARTED = "AI_ANALYSIS_STARTED"
    AI_ANALYSIS_COMPLETE = "AI_ANALYSIS_COMPLETE"
    AI_ANALYSIS_FAILED = "AI_ANALYSIS_FAILED"
    DELIVERY_COMPLETED = "DELIVERY_COMPLETED"
    DELIVERY_FAILED = "DELIVERY_FAILED"
    RETURN_READY = "RETURN_READY"
    RETURN_COLLECTED = "RETURN_COLLECTED"
    RETURN_CANCELLED = "RETURN_CANCELLED"
    STOP_CANCELLED = "STOP_CANCELLED"
    CAPACITY_CHANGED = "CAPACITY_CHANGED"
    TRAFFIC_DELAY = "TRAFFIC_DELAY"
    DRIVER_DELAY = "DRIVER_DELAY"
    REOPTIMIZING = "REOPTIMIZING"
    ROUTE_UPDATED = "ROUTE_UPDATED"


class SystemState(StrEnum):
    SCENARIO_READY = "SCENARIO_READY"
    OPTIMIZATION_RUNNING = "OPTIMIZATION_RUNNING"
    ROUTE_READY = "ROUTE_READY"
    TRIP_ACTIVE = "TRIP_ACTIVE"
    TRIP_CHANGED = "TRIP_CHANGED"
    REOPTIMIZING = "REOPTIMIZING"
    TRIP_COMPLETE = "TRIP_COMPLETE"


class ProviderStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
